# Dependencies
markdown:         kramdown
highlighter:      rogue
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Helt Sikker
tagline:          'Studentorganisasjon for datasikkerhet i Bergen'
description:      ''
url:              https://heltsikker.no
baseurl:          '/'

paginate:         5

# Custom vars
logo_url:       /public/hs_logo.png
